CREATE TABLE public.patients (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_code TEXT NOT NULL UNIQUE,
  full_name TEXT NOT NULL CHECK (char_length(full_name) BETWEEN 1 AND 100),
  age INTEGER NOT NULL CHECK (age BETWEEN 0 AND 130),
  gender TEXT NOT NULL CHECK (gender IN ('Female','Male','Non-binary','Other')),
  stage INTEGER NOT NULL CHECK (stage BETWEEN 1 AND 5),
  acuity_score INTEGER NOT NULL DEFAULT 0,
  category TEXT NOT NULL CHECK (category IN ('GREEN','YELLOW','RED')),
  status TEXT NOT NULL DEFAULT 'queue' CHECK (status IN ('queue','treatment','discharged')),
  room_code TEXT,
  systolic INTEGER,
  diastolic INTEGER,
  spo2 INTEGER,
  heart_rate INTEGER,
  respiration_rate INTEGER,
  pain INTEGER CHECK (pain BETWEEN 0 AND 10),
  consciousness TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  discharged_at TIMESTAMPTZ
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.patients TO authenticated;
GRANT ALL ON public.patients TO service_role;
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated staff manage patients" ON public.patients FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.resources (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  resource_type TEXT NOT NULL CHECK (resource_type IN ('doctor','nurse','intern','bed','equipment','ambulance')),
  resource_code TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  tier TEXT CHECK (tier IN ('ELE','ME','HE')),
  category TEXT CHECK (category IN ('GREEN','YELLOW','RED')),
  status TEXT NOT NULL CHECK (status IN ('available','engaged','maintenance','en_route')),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.resources TO authenticated;
GRANT ALL ON public.resources TO service_role;
ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated staff manage resources" ON public.resources FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.care_assignments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  resource_id UUID NOT NULL REFERENCES public.resources(id) ON DELETE RESTRICT,
  assignment_role TEXT NOT NULL CHECK (assignment_role IN ('doctor','nurse','intern','bed','equipment')),
  active BOOLEAN NOT NULL DEFAULT true,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  released_at TIMESTAMPTZ
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.care_assignments TO authenticated;
GRANT ALL ON public.care_assignments TO service_role;
ALTER TABLE public.care_assignments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated staff manage assignments" ON public.care_assignments FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.activity_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL,
  message TEXT NOT NULL CHECK (char_length(message) BETWEEN 1 AND 500),
  severity TEXT NOT NULL DEFAULT 'info' CHECK (severity IN ('info','warning','critical')),
  patient_id UUID REFERENCES public.patients(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.activity_events TO authenticated;
GRANT ALL ON public.activity_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.activity_events_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.activity_events_id_seq TO service_role;
ALTER TABLE public.activity_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated staff manage activity" ON public.activity_events FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE INDEX patients_live_status_idx ON public.patients(status, category, created_at);
CREATE INDEX assignments_patient_active_idx ON public.care_assignments(patient_id, active);
CREATE INDEX resources_type_status_idx ON public.resources(resource_type, status);